name: CI
on:
  pull_request_review:
    types: [submitted]
    # branches: ['master']

jobs:
  build:
    # The job runs on default machine
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout this repo branch
        uses: actions/checkout@v2
        if: github.event.review.state == 'approved'
      - name: Get the candidate branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: candidate
      - name: Git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git tag
          git describe
      - name: Merge candidate into master
        run: |
          echo running on branch ${GITHUB_REF##*/}
          git checkout master
          echo running on branch ${GITHUB_REF##*/}
          git merge --no-ff ${{ steps.candidate.outputs.branch }}
      - name: Run checks
        run: ./scripts/run-checks.sh
