name: integration
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    # The job runs on default novum machine
    runs-on: self-hosted
    steps:
      - name: Dummy Integration
        run: echo "Integration OK!!"