name: prlint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [master]

jobs:
  build:
    # The job runs on default machine
    runs-on: self-hosted
    env:
      TARGET_BRANCH: master
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout this repo branch
        uses: actions/checkout@v2

      - name: Lint Title
        run: |
          set -x 

          # Validate pull request title format
          title="${{ github.event.pull_request.title }}"
          if [[ "$title" =~ ^NOV-[0-9]{6}:.*$ ]]; then
            echo "Title format is ok"
            exit 0
          fi

          # If pull request title is not valid, try to compose it from branch name
          # so that a branch like NOV-667788-whatever-feature ends up in 
          # 'NOV-667788: whatever feature'
          if [[ "$GITHUB_HEAD_REF" =~ ^(NOV-[0-9]{6})-(.*)$ ]]; then
            prefix=${BASH_REMATCH[1]}
            description=${BASH_REMATCH[2]}
            summary="$(echo $description | tr - ' ')"
            gh pr edit ${{ github.event.pull_request.number }} --title "$prefix: $summary"
          fi

          echo "Title does not have the proper format"
          exit 1

      - name: See the proposer of the PR and what assignees have
        if: ${{ github.event.pull_request.assignee == '' }}
        run: |
          echo "AUTHOR: ${{ github.event.pull_request.head.user.login }}"
          echo "ASSIGNEE: ${{ github.event.pull_request.assignee }}"
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee "${{ github.event.pull_request.head.user.login }}"

      # - name: Checkout robertomier/prlint repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: robertomier/prlint
      #     token: ${{ secrets.CHECKOUT_TOKEN }}
      #     path: .github/actions
      # - name: Pull request lint
      #   uses: ./.github/actions
