name: prlint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [master]

jobs:
  build:
    # The job runs on default machine
    runs-on: self-hosted
    env:
      TARGET_BRANCH: master
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout this repo branch
        uses: actions/checkout@v2

      - name: Lint Title
        run: |
          set -x 
          
          title="${{ github.event.pull_request.title }}"
          if [[ "$title" =~ ^NOV-[0-9]{6}:.*$ ]]; then
            echo "Title format is ok"
            exit 0
          fi
          
          branch_name="$(git rev-parse --abbrev-ref HEAD)"
          if [[ "$branch_name" =~ ^(NOV-[0-9]{6})-(.*)$ ]]; then
            prefix=${BASH_REMATCH[1]}
            description=${BASH_REMATCH[2]}
            summary="$(echo $description | tr - ' ')"
            gh pr edit --title "$prefix: $summary"
            exit 0
          fi

          echo "Title does not have the proper format"
          exit 1

      - name: See the proposer of the PR and what assignees have
        if: ${{ github.event.pull_request.assignee == '' }}
        run: |
          echo "AUTHOR: ${{ github.event.pull_request.head.user.login }}"
          echo "ASSIGNEE: ${{ github.event.pull_request.assignee }}"
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee "${{ github.event.pull_request.head.user.login }}"

      # - name: Checkout robertomier/prlint repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: robertomier/prlint
      #     token: ${{ secrets.CHECKOUT_TOKEN }}
      #     path: .github/actions
      # - name: Pull request lint
      #   uses: ./.github/actions
