name: release

### VER
#
# gh pr list -s merged -B main -S be549926d92658f0aa5c5bf432e569b680926104 --json labels
#
# gh pr list -s merged -B master -S 3d972ded79ed8907a7ebe6ca0472ee48502d85dd --json labels -q '.[].labels[].name'
on:
  workflow_dispatch:
    branches: [master]
    inputs:
      bump_type:
        type: choice
        description: The type of version increment
        options: 
        - revision
        - minor
        - major

  workflow_run:
    workflows: [integration]
    type:
      - completed

jobs:
  build:
    # The job runs on default novum machine
    runs-on: self-hosted

    # Run only if integration was success or on demand
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - if: ${{ inputs.bump_type == '' }}
        name: calculate the bump version, when not set as input, based on last pr labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #/bin/bash 

          set -eou pipefail

          BUMP="revision"

          # searches for a certain label in the pr which landed a commit
          # $1 commit
          # $2 label
          commit_pr_has_label() {
            local pr_number
            local label
            commit="$1"
            label="$2"
            
            if gh pr list -s merged -B master -S "$commit" --json labels -q '.[].labels[].name' | grep "$label" > /dev/null 2>&1; then 
              return 0
            fi
            return 1
          }

          last_commit="$(git log -1 --oneline | cut -d ' ' -f1 | xargs)"

          if commit_pr_has_label "$last_commit" "feature"; then
            BUMP="minor"
          fi

          if commit_pr_has_label "$last_commit" "not backwards compatible"; then
            BUMP="major"
          fi

      - name: Echo the value of inputs.bump_type
        run: |
          echo "inputs bump_type: "${{ inputs.bump_type }}
